### ISSUE TITLE
Add option to delete invoke messages

### ISSUE THREAD

**Issue by ModdyLP** [Milotrince/discord-roombot#1]
Add a option in the settings that the invoke messages can be deleted automatic from the bot. 

Note: Nice Bot, I really like it.

**Comment by Milotrince** [comment]
Hi ModdyLP,
I'm glad you like the bot, and sorry for the late reply.
Do you mean that you want the person's command message, ex "r.new My Room" to be deleted?

**Comment by ModdyLP** [comment]
Yes exactly, that is what I mean

**Comment by Milotrince** [comment]
Alright, I added the option. If you are running your own RoomBot, edit the `config.json` to:
```
{
    "token": "TOKEN",
    "prefix": "r.",
    "timeout": 300,
    "respond_to_invalid_command": "true",
    "delete_command_message": "true"
}
```
Thanks for the suggestion 👍
