### ISSUE TITLE
in a room while im not

### ISSUE THREAD

**Issue by infosquad** [Milotrince/discord-roombot#2]
The bot keeps telling me im in a room already when I try to make a new one. then once I try to exit or disband it gives me a "something went wrong message" ive tried kicking and inviting the bot again and nothing changes

**Comment by Milotrince** [comment]
Sorry for the late response. I am guessing something might have happened as I was changing the host of the bot. Have you tried the purge command? `r.purge -a -b`

**Comment by Shk2f** [comment]
Its not work r.purge -a -b 
![Screenshot_14](https://user-images.githubusercontent.com/56977415/67516244-fa8d1780-f6a8-11e9-8a28-029652363b58.png)

**Comment by Milotrince** [comment]
Purge command error was with a misspelled key value in the strings refactor update. It has been fixed
