### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Hendalf-DEV** [Milotrince/discord-roombot#3]
Hello i have a problem with the invites what i wanna to do?
![Screenshot_13](https://user-images.githubusercontent.com/56977415/67515920-4ab7aa00-f6a8-11e9-895c-daaa519ec705.png)
My discord Великий Стас#8467

**Comment by Milotrince** [comment]
Sorry, the issue was with my bot hosting. I tested it and it should be working now.
